name: Build, Push to Docker Hub, and Deploy to Droplet

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: your-dockerhub-username/your-app-name

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker build -t zedonboy/relay:${{ github.sha }} .
        docker push zedonboy/relay:${{ github.sha }}

    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Login to Docker Hub on Droplet
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          # Pull and run the new image
          docker pull zedonboy/relay:${{ github.sha }}
          docker stop app-container || true
          docker rm app-container || true
          docker run -d \
            --name app-container \
            -p 3000:3000 \
            --restart unless-stopped \
            zedonboy/relay:${{ github.sha }}
          
          # Cleanup old images
          docker image prune -af